apiVersion: v1
kind: Service
metadata:
  name: my-react-cv
spec:
  type: NodePort
  selector:
    app: my-react-cv
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-react-cv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react-cv
  template:
    metadata:
      labels:
        app: my-react-cv
    spec:
      terminationGracePeriodSeconds: 31
      containers:
        - name: my-react-cv
          image: master.justeatup.xyz:5000/myprojects/mycv
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always