version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:15.5.0
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install
      - run: npm run-script build
      - run: docker build . -t docker.pollsapp.xyz:5000/myprojects/mycv
      - run: docker push docker.pollsapp.xyz:5000/myprojects/mycv
